#!/bin/sh

set -e

bundle exec jekyll build
bundle exec htmlproofer ./_site  --check-sri=true
bundle exec rubocop -D --config .rubocop.yml
bundle exec script/validate-html
gem build jekyll-theme-hacker.gemspec
